version: '3.3'
services:
  postgres12:
      image: postgres:12-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
  keycloak:
    image: jboss/keycloak:latest
    ports:
        - "8080:8080"
    environment:
        - "KC_HEALTH_ENABLED=true"
        - "KC_DB=postgres"
        - "KC_DB_URL=jdbc:postgresql://postgres12:5432/keycloak"
        - "KC_DB_SCHEMA=public"
        - "KC_DB_USERNAME=keycloak"
        - "KC_DB_PASSWORD=password"
        - "KEYCLOAK_ADMIN=admin"
        - "KEYCLOAK_ADMIN_PASSWORD=password"
        - "PROXY_ADDRESS_FORWARDING=true"
    entrypoint: /opt/keycloak/bin/kc.sh start-dev       
    volumes:
      - ./keycloak/themes/custom:/opt/jboss/keycloak/themes/custom
    depends_on:
      - postgres12
volumes:
  postgres_data:
      driver: local